# -*- coding: utf-8 -*-
"""EDA - pbl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bP9yoI9m2vbRrl8k2jxWxlc6uF4QHSnv

# IMPORT LIBRARY & LOAD DATASET
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Mengatur tema visual biar estetik dan bersih
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 11

try:
    # Ditambahkan engine='python' dan on_bad_lines='skip' agar baris yang rusak dilewati
    df_prepo = pd.read_csv("/content/skincare_preprocessed.csv", engine='python', on_bad_lines='skip')
    df_cluster = pd.read_csv("/content/skincare_clustered.csv", engine='python', on_bad_lines='skip')
    print("✅ Berhasil memuat kedua dataset dengan Python Engine!")
except Exception as e:
    print(f"❌ Gagal memuat data karena: {e}")

"""# PREPO"""

print("\n INFORMASI DATA PREPROCESSED ")
print(df_prepo.info())

print("\n 5 BRAND TERATAS DALAM DATASET ")
print(df_prepo['brand'].value_counts().head(5))

# Visualisasi Distribusi Tipe Produk Skincare
plt.figure(figsize=(10, 5))
type_counts = df_prepo['type'].value_counts()
sns.barplot(x=type_counts.values, y=type_counts.index, palette="pastel")
plt.title("Distribusi Tipe Produk Skincare", fontsize=14, pad=15)
plt.xlabel("Jumlah Produk")
plt.ylabel("Tipe Produk")
plt.tight_layout()
plt.show()

"""# ANALISIS KONDISI/MASALAH KULIT SECARA UMUM"""

# Daftar kolom indikator kondisi kulit (fitur biner)
skin_concerns = [
    'Acne_Fighting', 'Acne_Trigger', 'Anti_Aging', 'Brightening', 'Dark_Spots',
    'Drying', 'Eczema', 'Hydrating', 'Irritating', 'Large_Pores', 'Oily',
    'Redness', 'Reduces_Irritation', 'Rosacea', 'Scar', 'Skin_Texture', 'Worsen_Oily'
]

# Menghitung rata-rata kemunculan fitur di seluruh dataset (Proporsi)
mean_concerns = df_prepo[skin_concerns].mean().sort_values(ascending=False)

plt.figure(figsize=(11, 6))
sns.barplot(x=mean_concerns.values, y=mean_concerns.index, palette="magma")
plt.title("Prevalensi Fitur / Klaim Skincare di Seluruh Dataset", fontsize=14, pad=15)
plt.xlabel("Proporsi Kemunculan (Persentase)")
plt.ylabel("Kondisi / Masalah Kulit")
plt.tight_layout()
plt.show()

"""# CLUSTERED"""

print("\n JUMLAH PRODUK DI SETIAP CLUSTER ")
print(df_cluster['cluster'].value_counts().sort_index())

# Grouping data berdasarkan cluster untuk mencari rata-rata tiap fitur kulit
cluster_profile = df_cluster.groupby('cluster')[skin_concerns].mean()

# Membuat Heatmap Karakteristik Cluster yang Estetik
plt.figure(figsize=(15, 8))
sns.heatmap(
    cluster_profile,
    annot=True,          # Menampilkan angka persentase di dalam kotak
    fmt=".1%",           # Format angka menjadi persentase (e.g., 85.5%)
    cmap="YlGnBu",       # Skema warna estetik (Kuning - Hijau - Biru)
    linewidths=.5,       # Garis pembatas antar kotak
    cbar_kws={'label': 'Proporsi Karakteristik Kulit'}
)
plt.title("Heatmap Karakteristik Kondisi Kulit per Cluster", fontsize=16, pad=20, weight='bold')
plt.ylabel("Nomor Cluster", fontsize=12)
plt.xlabel("Fitur / Masalah Kulit", fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Print ringkasan teks fitur dominan di tiap cluster
print("\n RINGKASAN FITUR UTAMA TIAP CLUSTER ")
for cluster_num in sorted(df_cluster['cluster'].unique()):
    print(f"\nCluster {cluster_num}:")
    top_features = cluster_profile.loc[cluster_num].sort_values(ascending=False).head(3)
    for feat, val in top_features.items():
        print(f"  - {feat}: {val:.2%}")